# Generated by Django 4.2.7 on 2023-11-17 10:20

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SsbBuyruq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='commoninformation',
            options={'verbose_name': 'Common Information', 'verbose_name_plural': 'Common Informations'},
        ),
        migrations.AlterModelOptions(
            name='commoninformationtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Common Information Translation'},
        ),
        migrations.AlterField(
            model_name='commoninformationtranslation',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='SsbBuyruqTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('file', models.FileField(blank=True, null=True, upload_to='ssb_buyruq/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home_app.ssbbuyruq')),
            ],
            options={
                'verbose_name': 'ssb buyruq Translation',
                'db_table': 'home_app_ssbbuyruq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RahbariyatTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('ism', models.CharField(max_length=256, verbose_name='ism')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home_app.rahbariyat')),
            ],
            options={
                'verbose_name': 'rahbariyat Translation',
                'db_table': 'home_app_rahbariyat_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
