# Generated by Django 4.2.7 on 2023-12-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resurs_app", "0002_alter_fan_yunalish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mavzu",
            name="fan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mavzus",
                to="resurs_app.fan",
            ),
        ),
    ]
