# Generated by Django 4.2.7 on 2023-11-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
