# Generated by Django 4.2.7 on 2023-11-29 11:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_app", "0003_adabiyot_alter_yangiliktranslation_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hamkorlartranslation",
            name="rasm",
        ),
        migrations.AddField(
            model_name="hamkorlartranslation",
            name="phone",
            field=models.CharField(
                blank=True, default=None, max_length=15, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="adabiyottranslation",
            name="nashr_yil",
            field=models.DateTimeField(verbose_name="nashr_yil"),
        ),
        migrations.AlterField(
            model_name="hamkorlartranslation",
            name="faoliyat",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="faoliyat"
            ),
        ),
    ]
