# Generated by Django 4.2.7 on 2023-11-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_app", "0004_remove_hamkorlartranslation_rasm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hamkorlartranslation",
            name="phone",
            field=models.CharField(
                blank=True, default=None, max_length=20, null=True, verbose_name="phone"
            ),
        ),
    ]
