# Generated by Django 4.2.7 on 2024-06-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_app", "0007_foydalimalumot_videocontent_yaratiladiganadabiyot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adabiyottranslation",
            name="file",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="", verbose_name="file"
            ),
        ),
    ]
