# Generated by Django 4.2.7 on 2023-11-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                ("rasm", models.ImageField(upload_to="Fan/rasm/", verbose_name="rasm")),
            ],
            options={
                "verbose_name": "Fan",
                "verbose_name_plural": "Fanlar",
            },
        ),
        migrations.CreateModel(
            name="Yunalish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
            ],
            options={
                "verbose_name": "Yunalish",
                "verbose_name_plural": "Yunalishlar",
            },
        ),
        migrations.CreateModel(
            name="Mavzu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "nazariy_malumot",
                    models.FileField(
                        upload_to="Fan/nazariy_malumot/", verbose_name="nazariy malumot"
                    ),
                ),
                ("media", models.URLField()),
                (
                    "taqdimot",
                    models.FileField(
                        upload_to="Fan/taqdimot/", verbose_name="taqdimot"
                    ),
                ),
                (
                    "topshiriq",
                    models.FileField(
                        upload_to="Fan/topshiriq/", verbose_name="topshiriq"
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resurs_app.fan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mavzu",
                "verbose_name_plural": "Mavzular",
            },
        ),
        migrations.AddField(
            model_name="fan",
            name="yunalish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resurs_app.yunalish"
            ),
        ),
    ]
